services:
  api:
    build:
      context: ../../apps/miniapp-api
      dockerfile: Dockerfile
    image: local/miniapp-api:dev

  web:
    build:
      context: ../../apps/miniapp-web
      dockerfile: Dockerfile
    image: local/miniapp-web:dev

